# Generated by Django 5.1.4 on 2026-02-25 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('season_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('lifetime_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('energy', models.IntegerField(default=6000)),
                ('max_energy', models.IntegerField(default=6000)),
                ('last_energy_update', models.DateTimeField(auto_now_add=True)),
                ('generation', models.IntegerField(default=1)),
                ('rank_score', models.IntegerField(default=0)),
                ('is_mining', models.BooleanField(default=False)),
                ('mining_started_at', models.DateTimeField(blank=True, null=True)),
                ('aggressor_level', models.FloatField(default=0)),
                ('fights_left', models.IntegerField(default=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.CharField(blank=True, default='', max_length=500)),
                ('is_shadow_banned', models.BooleanField(default=False)),
                ('referral_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('network_tier', models.CharField(choices=[('Neural Link', 'Neural Link'), ('Satellite Grid', 'Satellite Grid'), ('Quantum Mesh', 'Quantum Mesh'), ('Singularity', 'Singularity')], default='Neural Link', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['balance'], name='idx_profile_balance'), models.Index(fields=['aggressor_level'], name='idx_profile_aggressor')],
            },
        ),
    ]
