# Generated by Django 5.0.14 on 2026-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_sync_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='Bot opponent for PvP'),
        ),
    ]
