# Generated by Django 5.0.8 on 2026-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.userprofile',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ton_wallet_address',
            field=models.CharField(blank=True, default='', help_text='TON wallet address for payments', max_length=48),
        ),
    ]
