# Generated by Django 5.0.8 on 2026-03-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_botprofile_userprofile_ton_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ton_wallet_address',
            field=models.CharField(blank=True, default='', help_text='Connected TON wallet address (raw or user-friendly)', max_length=100),
        ),
    ]
