# Generated by Django 5.0.8 on 2026-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_ton_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='networth',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total earnings without expenses - peak capital that can only grow', max_digits=20),
        ),
    ]
