# Generated by Django 5.0.8 on 2026-03-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_networth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='week_earned',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Earned this week — reset every Monday', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lifetime_balance',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Legacy field — mirrors balance historically', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='networth',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total all-time earnings — never decreases', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='season_balance',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Earned this month/season — reset on season end', max_digits=20),
        ),
    ]
