# Generated by Django 5.0.8 on 2026-03-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_week_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='month_earned',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Earned this month — reset monthly', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='season_balance',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Earned this season — reset on season end only', max_digits=20),
        ),
    ]
