# Generated by Django 5.0.8 on 2026-03-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_month_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='peak_all_time_rank',
            field=models.IntegerField(default=0, help_text='Best all-time rank ever achieved (0 = unranked)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='peak_month_rank',
            field=models.IntegerField(default=0, help_text='Best monthly rank ever achieved (0 = unranked)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='peak_week_rank',
            field=models.IntegerField(default=0, help_text='Best weekly rank ever achieved (0 = unranked)'),
        ),
    ]
