# Generated by Django 5.0.8 on 2026-03-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_peak_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mining_toggle',
            field=models.DateTimeField(blank=True, help_text='Cooldown: last start/stop action', null=True),
        ),
    ]
