# Generated by Django 5.0.8 on 2026-03-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_mining_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_mining_until',
            field=models.DateTimeField(blank=True, help_text='Auto-miner active until (24h paid boost, no energy cost)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='energy_depleted_at',
            field=models.DateTimeField(blank=True, help_text='When energy last hit 0 (for notification stub)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='turbo_boost_until',
            field=models.DateTimeField(blank=True, help_text='Turbo x2 mining boost active until (24h paid boost)', null=True),
        ),
    ]
