# Generated by Django 5.0.8 on 2026-03-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_boost_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_auto_harvest',
            field=models.DateTimeField(blank=True, help_text='Last time auto-mining was harvested', null=True),
        ),
    ]
