# Generated by Django 5.0.8 on 2026-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_last_auto_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_attacks_initiated',
            field=models.IntegerField(default=0, help_text='Attacks initiated today (0=green/immune, 1-2=yellow, 3+=red/priority)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_attack_at',
            field=models.DateTimeField(blank=True, help_text='When user last initiated a PvP attack (for aggressor decay)', null=True),
        ),
    ]
