# Generated by Django 5.1.4 on 2026-02-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('social', 'Social'), ('referral', 'Referral'), ('wallet', 'Wallet'), ('partner', 'Partner'), ('daily', 'Daily')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('reward', models.IntegerField(default=0, help_text='CHASH reward amount')),
                ('action_url', models.URLField(blank=True, default='')),
                ('target_progress', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_key', models.CharField(blank=True, default='star', help_text='Lucide icon key', max_length=50)),
                ('button_label', models.CharField(blank=True, default='Start', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('mining', 'Mining'), ('upgrade', 'Upgrade'), ('ascend', 'Ascend'), ('pvp_attack', 'PvP Attack'), ('pvp_defend', 'PvP Defend'), ('quest_reward', 'Quest Reward'), ('referral_bonus', 'Referral Bonus'), ('payment', 'Payment'), ('season_reset', 'Season Reset'), ('admin_adjust', 'Admin Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'tx_type', 'created_at'], name='idx_tx_profile_type')],
            },
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('is_claimed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quests', to='economy.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('user', 'quest')},
            },
        ),
    ]
