# Generated by Django 5.0.8 on 2026-03-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_alter_transactionhistory_tx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='tx_type',
            field=models.CharField(choices=[('mining', 'Mining'), ('upgrade', 'Upgrade'), ('ascend', 'Ascend'), ('pvp_attack', 'PvP Attack'), ('pvp_defend', 'PvP Defend'), ('quest_reward', 'Quest Reward'), ('referral_bonus', 'Referral Bonus'), ('payment', 'Payment'), ('ton_payment', 'TON Payment'), ('season_reset', 'Season Reset'), ('admin_adjust', 'Admin Adjustment'), ('admin_give', 'Admin Give'), ('admin_take', 'Admin Take')], db_index=True, max_length=20),
        ),
    ]
