# Generated by Django 5.1.4 on 2026-02-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_chance', models.FloatField(default=0.5, help_text='Base win probability (0.0-1.0)')),
                ('win_multiplier', models.FloatField(default=1.3, help_text='Max multiplier on win (capped at 1.3)')),
                ('tax_percent', models.FloatField(default=10.0, help_text='Percentage burned from wager')),
                ('cooldown_same_opponent_minutes', models.IntegerField(default=30)),
                ('aggressor_increase_per_fight', models.FloatField(default=15.0)),
                ('daily_fight_limit', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'PvP Configuration',
                'verbose_name_plural': 'PvP Configuration',
            },
        ),
        migrations.CreateModel(
            name='PvPMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wager', models.DecimalField(decimal_places=4, max_digits=20)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], max_length=10)),
                ('attacker_delta', models.DecimalField(decimal_places=4, help_text='Balance change for attacker', max_digits=20)),
                ('defender_delta', models.DecimalField(decimal_places=4, help_text='Balance change for defender', max_digits=20)),
                ('tax_burned', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks_made', to='accounts.userprofile')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks_received', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attacker', 'defender', 'created_at'], name='idx_pvp_cooldown')],
            },
        ),
    ]
