# Generated by Django 5.1.4 on 2026-02-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('multiplier', models.FloatField(default=1.0)),
                ('requirement_type', models.CharField(choices=[('mined_amount', 'Mined Amount'), ('referrals', 'Referrals'), ('stars_payment', 'Stars Payment')], max_length=20)),
                ('requirement_value', models.IntegerField(default=0)),
                ('stars_cost', models.IntegerField(default=0, help_text='Cost in Telegram Stars if paid tier')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UpgradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(help_text='e.g. u1, u2', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('energy', 'Energy'), ('mining', 'Mining'), ('recharge', 'Recharge'), ('passive', 'Passive')], max_length=20)),
                ('base_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cost_multiplier', models.FloatField(default=1.5)),
                ('max_level', models.IntegerField(default=20)),
                ('benefit_per_level', models.FloatField(default=0, help_text='500 for energy, 0.005 for mining power, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'config_id'],
            },
        ),
        migrations.CreateModel(
            name='UserUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_upgrades', to='game.upgradeconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('user', 'config')},
            },
        ),
    ]
