# Generated by Django 5.0.8 on 2026-03-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(unique=True)),
                ('block_hash', models.CharField(max_length=20)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finder', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=10)),
                ('participants', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
