# Generated by Django 5.1.4 on 2026-02-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('verification', 'Identity Verification'), ('fight_refill', 'Fight Refill'), ('network_tier', 'Network Tier Upgrade')], max_length=20)),
                ('provider', models.CharField(choices=[('telegram_stars', 'Telegram Stars'), ('ton', 'TON')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, default=0, help_text='Amount in provider currency', max_digits=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('telegram_payment_charge_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_payment_charge_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'payment_type'], name='idx_payment_profile_type')],
            },
        ),
    ]
