# Generated by Django 5.0.8 on 2026-03-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_ton_wallet_address'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='ton_tx_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='TON transaction hash for on-chain verification (unique per payment)', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('verification', 'Identity Verification'), ('fight_refill', 'Fight Refill'), ('network_tier', 'Network Tier Upgrade'), ('energy_boost', 'Energy Boost'), ('multitap', 'Turbo Uplink'), ('autobot', 'Auto Miner'), ('pvp_recovery', 'PvP Recovery')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider'], name='idx_payment_provider'),
        ),
    ]
