# Generated by Django 5.1.4 on 2026-02-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='SeasonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('final_rank', models.IntegerField(default=0)),
                ('final_generation', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_history', to='accounts.userprofile')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='season.season')),
            ],
            options={
                'ordering': ['final_rank'],
                'unique_together': {('season', 'profile')},
            },
        ),
    ]
